version: '3'
services:
  apache:
    container_name: apache
    build: docker/apache
    volumes:
      - ./docker/apache/logs:/etc/httpd/logs
    tty: true
    privileged: true
    ports:
      - 80:80
    depends_on:
      - springboot

  springboot:
    container_name: springboot
    build: docker/springboot
    tty: true
    ports:
      - 8090:8080